language: python
python:
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y git build-essential libxml2-dev libxslt1-dev libpq-dev
install:
  - cp src/conf/conf.cfg-sample src/conf/conf.cfg
  - pip install -r requirements.txt
  - pip install pep8 coverage coveralls
  - npm install
  - npm run build

script:
  - nosetests --with-coverage --cover-package=web,crawler,plugins src/tests/*
  - pep8 --ignore=E126,E127,E128,W503 src/web/ src/crawler/ src/plugins/
after_success:
  - coveralls
