version: '3.2'
services:
  redis:
    image: redis
    ports:
      - 6379
  rabbitmq:
    image: rabbitmq
    ports:
      - 25672
      - 4369
      - 5671
      - 5672
  postgresql:
    image: postgres:11
